# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: windows-2016

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: 拉取本项目的源码
        uses: actions/checkout@master
        
      - name: 安装python
        uses: actions/setup-python@v2.1.4
        with:
          # Version range or exact version of a Python version to use, using SemVer's version range syntax.
          python-version: 3.6
          # The target architecture (x86, x64) of the Python interpreter.
          architecture: x86

      - name: 更新python模块
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install --upgrade wheel setuptools          
          
        
      - name: 下载onnxruntime源码
        uses: microsoft/onnxruntime@master
      
